apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: nextjsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app
        imagePullPolicy: IfNotPresent
        image: 10.30.19.132:8080/qlbh_uat/nextjs-app-sample:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
      imagePullSecrets:
      - name: nextjsapp-registry